# Generated by Django 4.2.5 on 2023-09-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narx', models.IntegerField()),
                ('oldindan_tolov', models.IntegerField()),
                ('ustama', models.IntegerField()),
                ('muddat', models.IntegerField()),
                ('sana', models.DateField()),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-sana'],
            },
        ),
    ]
